# Numpy
Numpy ajoute le type **array** qui est similaire à une liste (list) avec la condition supplémentaire que tous les éléments sont du même type.

In [18]:
import numpy as np
# Créer un tableau. Le deuxième argument est optionnel. 
a = np.array([1, 4, 5, 8], float)    
print(a)
print(type(a))

[1. 4. 5. 8.]
<class 'numpy.ndarray'>


**Modifier une donnée d’une extraction d’un tableau entraîne aussi une modification du tableau initial **

In [19]:
import numpy as np
a=np.array([1, 2, 3, 4, 5])
c=np.array([1, 2, 3, 4, 5])
b=a[1:3]                     # [2 3]
b[1]=0
print(a)                     # a modifié
d=c[1:3].copy()              # ou np.copy(c[1:3])
d[1]=0
print(c)                     # c non modifié

[1 2 0 4 5]
[1 2 3 4 5]


## Slicing

In [3]:
import numpy as np
a = np.arange(10)           # [0 1 2 3 4 5 6 7 8 9]
b = a[2:9:3]                # [début:fin:pas]   renvoie [2 5 8]
c = a[:5]                   # fin exclue
d = a[5:]                   # début inclus 
e = a[9:0:-1]               # pb a[0] exclu
f = a[:]
g = a[-2::1]                # -2: l'avant dernier et le dernier terme :1 avec 
                            # un pas de 1
h = np.size(a)  

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

[0 1 2 3 4 5 6 7 8 9]
[2 5 8]
[0 1 2 3 4]
[5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
[0 1 2 3 4 5 6 7 8 9]
[8 9]
10


In [6]:
import numpy as np
a = np.array ([[1,2,3], [4,5,6], [7,8,9]])
b = a*2
c = a + b
d = np.dot(a, b)    # produit de A par B. 
                    # a*b renvoie le produit terme à terme 

print("A = ", a)
print("2A = ", b)
print("A + 2A = ", c)
print("A * 2A = ", d)

A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
2A =  [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
A + 2A =  [[ 3  6  9]
 [12 15 18]
 [21 24 27]]
A * 2A =  [[ 60  72  84]
 [132 162 192]
 [204 252 300]]


a = np.array([1,2])
b = np.outer(a,a) 


$\left (\begin{matrix}
1&2
\end{matrix}\right)$ 

$\left (\begin{matrix}
1&a\\ a&2
\end{matrix}\right)$

In [9]:
import numpy as np
a = np.array([1,2])
b = np.outer(a,a)
print(a)
print(b)

[1 2]
[[1 2]
 [2 4]]
